In [53]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [54]:
%cd '/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db'
!ls

/content/drive/My Drive/Colab Notebooks/Pandas - Platzi/db
covid_19_data.csv		     poblacion.csv  test.parquet
GlobalLandTemperaturesByCountry.csv  test.csv	    test.pkl
london_merged.csv		     test.hdf	    test.xlsx
Meteorite_Landings.csv		     test.json

In [55]:
import pandas as pd
import numpy as np
pd.__version__

'1.3.5'

In [56]:
df_pob = pd.read_csv('poblacion.csv')
df_pob

                       Country  year             pop
0                  Afghanistan  2015    34,413,603.0
1                      Albania  2015     2,880,703.0
2                      Algeria  2015    39,728,025.0
3               American Samoa  2015        55,812.0
4                      Andorra  2015        78,011.0
...                        ...   ...             ...
1035  Pre-demographic dividend  2018   919,485,393.0
1036              Small states  2018    40,575,321.0
1037                South Asia  2018 1,814,388,744.0
1038   South Asia (IDA & IBRD)  2018 1,814,388,744.0
1039        Sub-Saharan Africa  2018 1,078,306,520.0

[1040 rows x 3 columns]

In [57]:
pd.options.display.float_format = '{:,.1f}'.format
df_pob

                       Country  year             pop
0                  Afghanistan  2015    34,413,603.0
1                      Albania  2015     2,880,703.0
2                      Algeria  2015    39,728,025.0
3               American Samoa  2015        55,812.0
4                      Andorra  2015        78,011.0
...                        ...   ...             ...
1035  Pre-demographic dividend  2018   919,485,393.0
1036              Small states  2018    40,575,321.0
1037                South Asia  2018 1,814,388,744.0
1038   South Asia (IDA & IBRD)  2018 1,814,388,744.0
1039        Sub-Saharan Africa  2018 1,078,306,520.0

[1040 rows x 3 columns]

Transformar a tipo categorical para uso de multiples indices

In [58]:
df_pob['year'] = pd.Categorical(df_pob['year'].apply(str))

In [59]:
df_pob.dtypes

Country      object
year       category
pop         float64
dtype: object

In [60]:
idx_filtro = df_pob['Country'].isin(['Uruguay','Colombia'])
idx_filtro

0       False
1       False
2       False
3       False
4       False
        ...
1035    False
1036    False
1037    False
1038    False
1039    False
Name: Country, Length: 1040, dtype: bool

In [61]:
df_sample = df_pob[idx_filtro]
df_sample

      Country  year          pop
42   Colombia  2015 47,520,667.0
207   Uruguay  2015  3,412,009.0
302  Colombia  2016 48,171,392.0
467   Uruguay  2016  3,424,132.0
562  Colombia  2017 48,901,066.0
727   Uruguay  2017  3,436,646.0
822  Colombia  2018 49,648,685.0
987   Uruguay  2018  3,449,299.0

Creamos multiples index: sort_index() crea los niveles y combinacion de index

In [62]:
df_sample = df_sample.set_index(['Country','year']).sort_index()
df_sample

                       pop
Country  year
Colombia 2015 47,520,667.0
         2016 48,171,392.0
         2017 48,901,066.0
         2018 49,648,685.0
Uruguay  2015  3,412,009.0
         2016  3,424,132.0
         2017  3,436,646.0
         2018  3,449,299.0

In [63]:
df_sample.loc['Colombia',:]

              pop
year
2015 47,520,667.0
2016 48,171,392.0
2017 48,901,066.0
2018 49,648,685.0

In [64]:
df_sample.loc['Colombia',:].loc['2016',:]

pop   48,171,392.0
Name: 2016, dtype: float64

In [65]:
df_sample.xs(['Uruguay'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  """Entry point for launching an IPython kernel.

             pop
year
2015 3,412,009.0
2016 3,424,132.0
2017 3,436,646.0
2018 3,449,299.0

In [66]:
df_sample.xs(['Uruguay','2018'])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  """Entry point for launching an IPython kernel.

pop   3,449,299.0
Name: (Uruguay, 2018), dtype: float64

In [67]:
df_sample.xs('2018', level='year')

                  pop
Country
Colombia 49,648,685.0
Uruguay   3,449,299.0

In [68]:
df_countries = df_pob.set_index(['Country','year']).sort_index(ascending = [True,True])
df_countries

                          pop
Country     year
Afghanistan 2015 34,413,603.0
            2016 35,383,128.0
            2017 36,296,400.0
            2018 37,172,386.0
Albania     2015  2,880,703.0
...                       ...
Zambia      2018 17,351,822.0
Zimbabwe    2015 13,814,629.0
            2016 14,030,390.0
            2017 14,236,745.0
            2018 14,439,018.0

[1040 rows x 1 columns]

In [69]:
ids = pd.IndexSlice
df_countries.loc[ids['Argentina':'Austria','2015':'2017'],:].sort_index()

                        pop
Country   year
Argentina 2015 43,131,966.0
          2016 43,590,368.0
          2017 44,044,811.0
Armenia   2015  2,925,553.0
          2016  2,936,146.0
          2017  2,944,809.0
Aruba     2015    104,341.0
          2016    104,872.0
          2017    105,366.0
Australia 2015 23,815,995.0
          2016 24,190,907.0
          2017 24,601,860.0
Austria   2015  8,642,699.0
          2016  8,736,668.0
          2017  8,797,566.0

In [70]:
df_countries.index.get_level_values(0)

Index(['Afghanistan', 'Afghanistan', 'Afghanistan', 'Afghanistan', 'Albania',
       'Albania', 'Albania', 'Albania', 'Algeria', 'Algeria',
       ...
       'Yemen, Rep.', 'Yemen, Rep.', 'Zambia', 'Zambia', 'Zambia', 'Zambia',
       'Zimbabwe', 'Zimbabwe', 'Zimbabwe', 'Zimbabwe'],
      dtype='object', name='Country', length=1040)

In [71]:
df_countries.index.get_level_values(1)

CategoricalIndex(['2015', '2016', '2017', '2018', '2015', '2016', '2017',
                  '2018', '2015', '2016',
                  ...
                  '2017', '2018', '2015', '2016', '2017', '2018', '2015',
                  '2016', '2017', '2018'],
                 categories=['2015', '2016', '2017', '2018'], ordered=False, dtype='category', name='year', length=1040)

In [72]:
df_countries['pop']['Colombia']['2018']

49648685.0

In [73]:
df_countries.sum(level='year')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  """Entry point for launching an IPython kernel.

                  pop
year
2015 65,679,147,019.0
2016 66,487,930,677.0
2017 67,294,176,701.0
2018 68,087,886,692.0

In [74]:
df_sample

                       pop
Country  year
Colombia 2015 47,520,667.0
         2016 48,171,392.0
         2017 48,901,066.0
         2018 49,648,685.0
Uruguay  2015  3,412,009.0
         2016  3,424,132.0
         2017  3,436,646.0
         2018  3,449,299.0

In [75]:
df_sample.unstack('year')

                  pop
year             2015         2016         2017         2018
Country
Colombia 47,520,667.0 48,171,392.0 48,901,066.0 49,648,685.0
Uruguay   3,412,009.0  3,424,132.0  3,436,646.0  3,449,299.0

unstack: convierte filas en columnas

In [76]:
df_sample.unstack('Country')

                 pop
Country     Colombia     Uruguay
year
2015    47,520,667.0 3,412,009.0
2016    48,171,392.0 3,424,132.0
2017    48,901,066.0 3,436,646.0
2018    49,648,685.0 3,449,299.0

In [81]:
df_countries['pop']['Colombia']['2018']
df_countries.loc[ids[:,'2018'],:].sort_index()

                                    pop
Country               year
Afghanistan           2018 37,172,386.0
Albania               2018  2,866,376.0
Algeria               2018 42,228,429.0
American Samoa        2018     55,465.0
Andorra               2018     77,006.0
...                                 ...
Virgin Islands (U.S.) 2018    106,977.0
West Bank and Gaza    2018  4,569,087.0
Yemen, Rep.           2018 28,498,687.0
Zambia                2018 17,351,822.0
Zimbabwe              2018 14,439,018.0

[260 rows x 1 columns]